<?php

namespace Nox\LastChaos\Filament\Resources\CharacterResource\RelationManagers;

use Filament\Resources\RelationManagers\RelationManager;

class InventoryRelationManager extends RelationManager
{
    protected static string $relationship = 'inventory_rows';

    protected function getViewData(): array
    {
        dd($this->getTableRecords());
        return parent::getViewData(); // TODO: Change the autogenerated stub
    }
}